= 1-) Sanal Makine Kurulumu

.. *İçindekiler*
. Sanal Makine Kurulumu
.. Giriş
... Sanal Makine Programı
.... VirtualBox Sanal Makinesinin Kurulumu
... Sanal Makine Dosyası
.. Güvenlik Notları
.. İlk Çalıştırma
.. Sanal Makinenin Kullanımı


== 1.2. Giriş
Sistem Programlama için kullanılacak geliştirme ortamı kurulumu iki adıma ihtiyaç duymaktadır. + 

* Sanal Makine Programı(VirtualBox) +

* Sanal Makine Dosyasının Kurulumu(xubuntu-kouembedded-v20160217.ova) +

=== 1.2.1. Sanal Makine Programı

Sanal Makine programları gerçek bir bilgisayar gibi çalışan yazılımdır. Sanal Makine, işletim sistemi ile donanım arasında bir sanal ortam oluşturur. +

==== 1.2.1.1. VirtualBox Sanal Makinesinin Kurulumu

Sistem programlama dersi için hazırlanan geliştirme ortamı VirtualBox isimli bir sanal makine programı üzerinde çalışacaktır. VirtualBox sanal makine programı aşağıdaki linklerden indirilip kurulabilir. +

* Windows: http://download.virtualbox.org/virtualbox/4.3.36/VirtualBox-4.3.36-105129-Win.exe/

* GNU/Linux: Yazılım merkezi kullanılarak indirilebilir. +

* OS X: http://download.virtualbox.org/virtualbox/4.3.36/VirtualBox-4.3.36-105129-OSX.dmg/

VirtualBox kurulumu tamamlandıktan sonra programa ait birkaç özelliğin aktif hale gelmesi için aşağıdaki linkteki ek paketinde indirilip kurulması gerekmektedir.+

http://download.virtualbox.org/virtualbox/4.3.36/Oracle_VM_VirtualBox_Extension_Pack-4.3.36-105129.vbox-extpack/


